<?php

require_once dirname(__FILE__).'/../../../lib/Simph/Router.php';

/**
 * Test class for Simph_Router_HttpException.
 * Generated by PHPUnit on 2011-08-29 at 22:54:12.
 */
class Simph_Router_HttpExceptionTest extends PHPUnit_Framework_TestCase {
    /**
     * @var Simph_Router_HttpException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Simph_Router_HttpException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }
}
?>
