<?php

require_once dirname(__FILE__).'/../../../lib/Simph/Router.php';

/**
 * Test class for Simph_Router_Route.
 * Generated by PHPUnit on 2011-08-29 at 22:54:15.
 */
class Simph_Router_RouteTest extends PHPUnit_Framework_TestCase {
    /**
     * @var Simph_Router_Route
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Simph_Router_Route;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testDef().
     */
    public function testDef() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMatch().
     */
    public function testMatch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetPath().
     */
    public function testGetPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
?>
